/* moalib.c - This module contains some utility functions used at run time
     by the C procedures generated by the PSI Compiler */

#include <stdlib.h>


int min(int a, int b)

{
  return((a<b) ? a : b);
}


int max(int a, int b)

{
  return((a>b) ? a : b);
}


void *get_mem(long size)

{
  void *ret;

  if (size==0) {
    ret=NULL;
  } else {
    if ((ret=malloc(size))==NULL) {
      puts("Out of memory!");
      exit(1);
    }
  }
 
  return(ret);
}
  

