! network.f90 - This module contains some utility functions used at run time
! by the F90 procedures generated by the PSI Compiler

       MODULE MPINET

       INTERFACE MPI_Send
         SUBROUTINE MPI_Send (PTR, SIZE, PROC)
           REAL, DIMENSION (:) :: PTR
           INTEGER :: SIZE, PROC
         END SUBROUTINE MPI_Send
       END INTERFACE
 
         INTERFACE MPI_Recv
         SUBROUTINE MPI_Recv (PTR, SIZE, PROC)
           REAL, DIMENSION (:) :: PTR
           INTEGER :: SIZE, PROC
         END SUBROUTINE MPI_Recv
       END INTERFACE
  
       INTERFACE MPI_Init
         SUBROUTINE MPI_Init (ARGC, ARGV)
           INTEGER :: ARGC
           CHARACTER, POINTER :: ARGV
         END SUBROUTINE MPI_Init
       END INTERFACE

       CONTAINS

       FUNCTION MY_PROC ()
         MY_PROC = 0 ! MPI_MY_NODE ()
       END FUNCTION

       SUBROUTINE SEND (PTR, SIZE, PROC)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE, PROC

         PRINT *, "SEND CALLED"
!        call MPI_Send (PTR, SIZE, PROC);
       END SUBROUTINE

       SUBROUTINE RECV (PTR, SIZE, PROC)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE, PROC
       
!        call MPI_Recv (PTR, SIZE, PROC)
       END SUBROUTINE
       
       SUBROUTINE SEND_HOST (PTR, SIZE)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE
       
!        call MPI_Send (PTR, SIZE, 0);
       END SUBROUTINE
       
       SUBROUTINE RECV_HOST (PTR, SIZE)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE
       
!        call MPI_Recv (PTR, SIZE, 0)
       END SUBROUTINE
       
       SUBROUTINE HOST_SEND (PTR, SIZE, PROC)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE, PROC
       
!        call MPI_Send (PTR, SIZE, PROC);
       END SUBROUTINE
       
       SUBROUTINE HOST_RECV (PTR, SIZE, PROC)
         REAL, DIMENSION (:) :: PTR 
         INTEGER :: SIZE, PROC
       
!        call MPI_Recv (PTR, SIZE, PROC)
       END SUBROUTINE
       
       SUBROUTINE HOST_INIT ()
       END SUBROUTINE
!      SUBROUTINE HOST_INIT (ARGC, ARGV)
!        INTEGER :: ARGC
!        CHARACTER, POINTER :: ARGV
!      
!        call MPI_Init (ARGC, ARGV)
!      END SUBROUTINE
       
       SUBROUTINE HOST_CLEANUP ()
!        call MPI_Finalize ()
       END SUBROUTINE
       
       SUBROUTINE NODE_INIT ()
       END SUBROUTINE
!      SUBROUTINE NODE_INIT (ARGC, ARGV)
!        INTEGER :: ARGC
!        CHARACTER, POINTER :: ARGV
!      
!        call MPI_Init ()
!      END SUBROUTINE 
      
       SUBROUTINE NODE_CLEANUP ()
!        call MPI_Finalize ()
       END SUBROUTINE
       
       SUBROUTINE WAIT ()
!        call MPI_WAIT ()
       END SUBROUTINE
       
       END MODULE
