actual           726 parse.c          expr_t *actual()
actual_list      749 parse.c          statement_t *actual_list()
addto_allocs     718 code.c           addto_allocs(expr_t *expr)
addto_dynamics   732 code.c           addto_dynamics(expr_t *expr)
addto_reduced    132 psi.c            addto_reduced(expr_t *expr, expr_t *result, char *op)
add_allocation   117 psi.c            add_allocation(expr_t *expr)
add_rule          31 part.c           rule_t *add_rule(ident_t *ident, vect_t *shp)
add_steps        970 code.c           add_steps(vect_t *bound, vect_t *shp1, vect_t *stride, s_expr_t *dim,
allocate         673 parse.c          statement_t *allocate()
allocate_actuals1539 code.c           allocate_actuals(reduced_t *list)
allocate_array   747 code.c           allocate_array(ident_t *ident)
allocate_utils  1409 dist.c           allocate_utils()
allocate_vect    267 code.c           void allocate_vect(ident_t *ident)
array_def        850 parse.c          array_def(ident_t *ident)
assign           663 psi.c            expr_t *assign(expr_t *expr, expr_t *result, int top, char *op, int inright)
assignment       592 parse.c          statement_t *assignment()
assignment_part  627 parse.c          statement_t *assignment_part(vect_t *loc, int index, char *name)
assign_rav       269 psi.c            assign_rav(expr_t *rav, expr_t *expr, expr_t *result, 
bFindUniqueIdentifiers 139 scalar.c         int bFindUniqueIdentifiers(s_expr_t *pseNode) {
bGetDim           91 values.c         int bGetDim(parser_t *arg, double *dim) {
bGetIdentValue    30 values.c         int bGetIdentValue(ident_t *node, int index, double *value) {
bGetShp          114 values.c         int bGetShp(parser_t *arg, int dim, double *shp) {
bGetSingleDimParserValue 137 values.c         int bGetSingleDimParserValue(parser_t *arg, int index, double *value) {
blockbody       1017 parse.c          statement_t *blockbody()
block_rav        209 psi.c            block_rav(s_expr_t *i, s_expr_t *b, vect_t *s, vect_t *bound, vect_t *index,
build_rule        70 part.c           build_rule(expr_t *expr, expr_t *res)
build_vect       146 dist.c           vect_t *build_vect(char *name, s_expr_t *shp)
call_statement   778 parse.c          statement_t *call_statement(char *name)
check_combined_temps 987 psi.c            check_combined_temps(reduced_t *ret, reduced_t **non_assigns)
check_zero       169 dist.c           int check_zero(vect_t *vect)
cleanup           34 main.c           void cleanup()
clear_saves      364 sys.c            clear_saves()
clear_syms        79 parse.c          clear_syms()
close_forall    1515 code.c           close_forall(expr_t *fa_expr)
close_while      275 dist.c           close_while(FILE *fd, vect_t *s, vect_t *s_bound, char *cont)
code_c          1725 code.c           code_c(statement_t *body, dist_t *dist)
code_c_rec      1739 code.c           code_c_rec(statement_t *body)
code_dist       1027 dist.c           code_dist(reduced_t *list, expr_t *res, dist_t *l_dist)
code_expr       1604 code.c           code_expr(reduced_t *reduced)
code_extended      7 extended.c       code_extended (reduced_t *node)
code_global_int 1116 dist.c           code_global_int(ident_t *ident)
code_idx_array   709 code.c           void code_idx_array (char *where, char *array, char *index)
code_reduced    1663 code.c           code_reduced(reduced_t *reduced)
code_vect        453 code.c           code_vect(vect_t *vect, vect_t *res, char *op, char *pre ,char *post, 
collect_garbage  569 sys.c            collect_garbage(reduced_t *reduced, save_t *list, dist_t *dist)
collect_mem      622 sys.c            collect_mem()
collect_reduced  531 sys.c            collect_reduced(reduced_t *reduced)
combine_distributed 321 dist.c           reduced_t *combine_distributed(reduced_t *reduced)
combine_reduced 1061 psi.c            reduced_t *combine_reduced(reduced_t *reduced, expr_t *result, int inloop)
compactor        271 ident.c          s_expr_t *compactor(s_expr_t *s, int *changed)
const_def        947 parse.c          const_def()
const_def_part   977 parse.c          const_def_part()
const_op         152 vect.c           vect_t *const_op(vect_t *arg, vect_t *res, int size, int op)
convert_shp      222 parse.c          convert_shp(ident_t **ident_p, expr_t *expr, ident_t *dim)
copy_expr        374 sys.c            expr_t *copy_expr(expr_t *expr)
copy_list         85 dist.c           reduced_t *copy_list(reduced_t *list)
debug_ident        6 debug.c          void debug_ident (ident_t *ident)
debug_s_expr      26 debug.c          void debug_s_expr (s_expr_t *s)
debug_vect        37 debug.c          void debug_vect (vect_t *v)
declare_utils     67 code.c           void declare_utils ()
declare_var       86 code.c           void declare_var (int integer, char *name, int len)
define           127 lex.c            define(uchar isname, char *name, int index)
def_part        1005 parse.c          def_part()
directive       1227 parse.c          directive()
dist_array      1241 dist.c           dist_array(dist_t *dist)
dist_assign      715 dist.c           dist_assign(reduced_t *list, vect_t *loc_adj, vect_t *ip, vect_t *lp,
dist_compare      68 dist.c           int dist_compare(dist_t *dist1, dist_t *dist2)
dist_init       1439 dist.c           dist_init()
dist_lhs         370 dist.c           vect_t *dist_lhs(expr_t *expr, expr_t *res, dist_t *l_dist, vect_t *ip, 
dist_rhs         553 dist.c           vect_t *dist_rhs(expr_t *expr, dist_t *r_dist, vect_t *ip, vect_t *lp, 
dotab            387 sys.c            dotab(int adj)
dotabf           397 sys.c            dotabf(FILE *fd, int adj)
do_assign       1416 code.c           do_assign(expr_t *expr, expr_t *result)
do_gamma         951 code.c           do_gamma(expr_t *expr, expr_t *result, int num)
do_location      921 code.c           int do_location(expr_t *expr, expr_t *result)
do_loop_close   1130 code.c           do_loop_close(s_expr_t *dim, vect_t *bound, s_expr_t *rdim)
do_loop_open    1100 code.c           do_loop_open(vect_t *bound, s_expr_t *dim)
do_ptab          411 sys.c            do_ptab(int adj)
do_shapes        801 code.c           do_shapes(expr_t *expr, expr_t *result)
dup_expr         189 psi.c            expr_t *dup_expr(expr_t *expr)
eDIM               5 macros.h         #define eDIM(expr) expr->dim
embed_const_vect 301 code.c           embed_const_vect(ident_t *ident)
empty            162 psi.c            int empty(vect_t *vect)
end_loop        1467 code.c           end_loop(int depth)
error            248 sys.c            void error(char *msg)
eSHAPE             3 macros.h         #define eSHAPE(expr) expr->shp
expand_vect      884 vect.c           vect_t *expand_vect(vect_t *vect)
expect           162 parse.c          expect(int sym)
expect_name      177 parse.c          int expect_name()
expect_number    192 parse.c          double expect_number()
expression       572 parse.c          parser_t *expression()
expr_free        125 sys.c            expr_free(expr_t *expr)
factor           542 parse.c          parser_t *factor()
fatal            256 sys.c            void fatal(char *msg)
find_dist         51 dist.c           dist_t *find_dist(ident_t *array)
find_rule         49 part.c           rule_t *find_rule(ident_t *ident)
find_sym          93 parse.c          ident_t *find_sym(int index,int talk)
find_temp        951 psi.c            int find_temp(reduced_t *list, char *name, int ex_num)
forall           560 psi.c            forall(expr_t *fa_expr, expr_t *result, int top, char *op, int inright)
forall_statement 699 parse.c          statement_t *forall_statement()
force_vect      1237 vect.c           vect_t *force_vect(vect_t *vect)
formal_list     1079 parse.c          formal_list()
FreeFractionalPolygon 650 scalar.c         void FreeFractionalPolygon(FractionalPolygon_t *pfpNew) {
free_poly         76 poly.c           void free_poly(poly_t *p)
free_tmp_mem     317 sys.c            void free_tmp_mem()
get_expr_mem      89 sys.c            expr_t *get_expr_mem(int n)
get_ident        176 sys.c            ident_t *get_ident()
get_mem           21 moalib.c         void *get_mem(long size)
get_statement    336 sys.c            statement_t *get_statement(int kind)
get_symbol       167 lex.c            get_symbol()
get_s_expr       214 sys.c            s_expr_t *get_s_expr()
get_tmp_mem      285 sys.c            void *get_tmp_mem(int size) 
get_vect         137 sys.c            vect_t *get_vect()
GLOBAL           230 psi.h            #define GLOBAL(x) (((x)&0x20)!=0)
global_assign   1245 code.c           global_assign(reduced_t *global, expr_t *result)
global_def       987 parse.c          global_def()
HASSHAPE         242 psi.h            #define HASSHAPE(x) (((x)&0x04)!=0)
IdentifierFound  204 scalar.c         void IdentifierFound(ident_t *pidIdentifier) {
ident_compare    505 ident.c          int ident_compare(ident_t *ident1, ident_t *ident2)
ident_free       202 sys.c            ident_free(ident_t *ident)
iDIM               4 macros.h         #define iDIM(ident) ident->array.dim
if_bounded       224 dist.c           if_bounded(vect_t *var, vect_t *lbound, vect_t *rbound, char *res, int out)
IndexIdentifiers 322 scalar.c         void IndexIdentifiers (BinaryTreeNode_t *pbtnCurrent) {
index_vect       191 dist.c           index_vect(vect_t *vect, char *index)
init_dist_arrays1365 dist.c           init_dist_arrays(dist_t *dist)
insert           106 lex.c            symbol_t *insert(uchar isname, char *name, int index, int key)
insert_sym       110 parse.c          insert_sym(ident_t *ident, int index)
inv_gamma        112 dist.c           inv_gamma(char *rav, vect_t *shp, char *res)
iota_loop_close 1221 code.c           iota_loop_close(s_expr_t *dim, vect_t *bound)
iota_loop_open  1189 code.c           iota_loop_open(vect_t *index, vect_t *bound, s_expr_t *dim)
ISALLOC          255 psi.h            #define ISALLOC(x) (((x)&0x08)!=0)
ISCODED          250 psi.h            #define ISCODED(x) (((x)&0x01)!=0)
ISDYNAMIC        234 psi.h            #define ISDYNAMIC(x) (((x)&0x10)!=0)
iSHAPE             1 macros.h         #define iSHAPE(ident) ident->array.shp
isop             523 parse.c          int isop(int i)
ISPARAMETER      246 psi.h            #define ISPARAMETER(x) (((x)&0x02)!=0)
ISSCANNED        259 psi.h            #define ISSCANNED(x) (((x)&0x10)!=0)
ISUSED           238 psi.h            #define ISUSED(x) (((x)&0x08)!=0)
is_recursive      70 psi.c            int is_recursive(expr_t *expr, ident_t *result, int in_left)
is_unop          360 parse.c          int is_unop(int x)
key               90 lex.c            int key(char *name)
lex_init         305 lex.c            lex_init()
main              46 main.c           main(int argc, char *argv[])
make_ident        52 ident.c          ident_t *make_ident(s_expr_t *s)
make_s_expr       86 ident.c          s_expr_t *make_s_expr(vect_t *vect)
make_vect        442 vect.c           vect_t *make_vect(expr_t *expr)
mark_expr        494 sys.c            mark_expr(expr_t *expr)
mark_extended     11 extended.c       mark_extended (statement_t *node)
mark_ident       435 sys.c            mark_ident(ident_t *ident)
mark_ident_list  465 sys.c            mark_ident_list(ident_t *ident)
mark_s_expr      518 sys.c            mark_s_expr(s_expr_t *s_expr)
mark_vect        477 sys.c            mark_vect(vect_t *vect)
max               14 moalib.c         int max(int a, int b)
mem_init         684 sys.c            mem_init()
min                7 moalib.c         int min(int a, int b)
MYMAX             37 ident.c          #define MYMAX(x,y) ((x)>(y)) ? (x) : (y)
MYMIN             36 ident.c          #define MYMIN(x,y) ((x)<(y)) ? (x) : (y)
my_gamma         870 code.c           int my_gamma(FILE *out, char *name, vect_t *index, vect_t *shp, s_expr_t *dim)
my_gamma2        821 code.c           int my_gamma2(FILE *out, char *name, vect_t *index, vect_t *shp, s_expr_t *dim)
new_poly          61 poly.c           poly_t *new_poly(int d)
NEW_SCALAR       266 psi.h            #define NEW_SCALAR(i,number) \
nextchar          76 lex.c            nextchar()
NONASSOCIATIVE    42 psi.c            #define NONASSOCIATIVE(op) ((*op=='/')||(*op=='-'))
NOTALLOCATED      39 code.c           #define NOTALLOCATED(a) ((!ISUSED(a->flags))&&(!ISPARAMETER(a->flags))&&(a->type!=RAV)&&(a->type!=CONST_ARRAY)&&(a->type!=CONSTANT)&&(a->type!=IOTA))
open_forall     1483 code.c           open_forall(expr_t *fa_expr)
param_def       1030 parse.c          param_def()
partition        231 part.c           dist_t *partition(statement_t *body)
partition_reduced 162 part.c           partition_reduced(reduced_t *reduced)
pfpFractionalPolygonAdd 494 scalar.c         FractionalPolygon_t *pfpFractionalPolygonAdd(FractionalPolygon_t *pfpLeft,
pfpFractionalPolygonTimes 447 scalar.c         FractionalPolygon_t *pfpFractionalPolygonTimes(FractionalPolygon_t *pfpLeft,
pfpSExprToFractionalPolygon 353 scalar.c         FractionalPolygon_t *pfpSExprToFractionalPolygon(s_expr_t *pseNode) {
pidGetBinaryTreeByIndex 285 scalar.c         ident_t *pidGetBinaryTreeByIndex (int iIndex, BinaryTreeNode_t *pbtnCurrent) {
poly_add         115 poly.c           poly_t *poly_add(poly_t *left, poly_t *right)
poly_constant    331 poly.c           poly_t *poly_constant(double c, int d)
poly_copy         89 poly.c           poly_t *poly_copy(poly_t *p)
poly_expand      312 poly.c           poly_t *poly_expand(int terms, double *p, int var, int d)
poly_print       348 poly.c           void poly_print(poly_t *p)
poly_scale       243 poly.c           poly_t *poly_scale(double k, int *j, poly_t *p)
poly_times       184 poly.c           poly_t *poly_times(poly_t *p1, poly_t *p2)
ppbtnGetBinaryTreeNode 240 scalar.c         BinaryTreeNode_t **ppbtnGetBinaryTreeNode (char *sIdentifier) {
print_expr       247 output.c         print_expr(int bottom,expr_t *expr, expr_t *result, char *op)
print_gen_ident   17 output.c         print_gen_ident(ident_t *ident)
print_ident      103 code.c           print_ident(FILE *outfile,ident_t *ident)
print_op         153 code.c           print_op(FILE *outfile, int op)
print_rav        344 code.c           print_rav(FILE *outfile, vect_t *vect,int i)
print_s          180 code.c           print_s(FILE *outfile,s_expr_t *s)
print_scalar     938 vect.c           print_scalar(vect_t *expr)
print_s_expr     149 ident.c          print_s_expr(FILE *outfile, s_expr_t *s)
print_vector      60 output.c         print_vector(vect_t *vect)
proc_def        1092 parse.c          proc_def()
programx        1279 parse.c          programx()
propagate_cat    833 vect.c           propagate_cat(vect_t *vect, s_expr_t *location)
propagate_drop   717 vect.c           propagate_drop(vect_t *vect, s_expr_t *index)
propagate_take   560 vect.c           propagate_take(vect_t *vect, s_expr_t *bound)
psePolyToSExpr   549 scalar.c         s_expr_t *psePolyToSExpr(poly_t *ppPoly) {
psi_access        40 moa_func.c       parser_t *psi_access(ident_t *ident)
psi_cat          491 moa_func.c       parser_t *psi_cat(parser_t *arg1, parser_t *arg2)
psi_dim          128 moa_func.c       parser_t *psi_dim(parser_t *arg1)
psi_div          458 moa_func.c       parser_t *psi_div(parser_t *left, parser_t *right)
psi_drop         280 moa_func.c       parser_t *psi_drop(parser_t *arg1, parser_t *arg2)
psi_init        1253 psi.c            psi_init()
psi_iota          97 moa_func.c       parser_t *psi_iota(parser_t *arg1)
psi_minus        448 moa_func.c       parser_t *psi_minus(parser_t *left, parser_t *right)
psi_omega1       528 moa_func.c       parser_t *psi_omega1(parser_t *arg2, op_t *op)
psi_omega2       604 moa_func.c       parser_t *psi_omega2(parser_t *arg1, parser_t *arg2, op_t *op)
psi_op           406 moa_func.c       parser_t *psi_op(int op, parser_t *arg1, parser_t *arg2)
psi_pdrop        323 moa_func.c       parser_t *psi_pdrop(parser_t *arg1, parser_t *arg2)
psi_plus         443 moa_func.c       parser_t *psi_plus(parser_t *left, parser_t *right)
psi_psi          463 moa_func.c       parser_t *psi_psi(parser_t *arg1, parser_t *arg2)
psi_ptake        302 moa_func.c       parser_t *psi_ptake(parser_t *arg1, parser_t *arg2)
psi_rav          207 moa_func.c       parser_t *psi_rav(parser_t *arg1)
psi_reduce      1196 psi.c            psi_reduce(statement_t *statement,int top)
psi_red_div      815 moa_func.c       parser_t *psi_red_div(parser_t *arg)
psi_red_minus    805 moa_func.c       parser_t *psi_red_minus(parser_t *arg)
psi_red_op       708 moa_func.c       parser_t *psi_red_op(int op, parser_t *arg)
psi_red_plus     800 moa_func.c       parser_t *psi_red_plus(parser_t *arg)
psi_red_times    810 moa_func.c       parser_t *psi_red_times(parser_t *arg)
psi_reshape      366 moa_func.c       parser_t *psi_reshape(parser_t *arg1, parser_t *arg2)
psi_reverse      345 moa_func.c       parser_t *psi_reverse(parser_t *arg1)
psi_rotate       371 moa_func.c       parser_t *psi_rotate(parser_t *arg1, parser_t *arg2)
psi_shp          186 moa_func.c       parser_t *psi_shp(parser_t *arg1)
psi_take         255 moa_func.c       parser_t *psi_take(parser_t *arg1, parser_t *arg2)
psi_tau          146 moa_func.c       parser_t *psi_tau(parser_t *arg1)
psi_times        453 moa_func.c       parser_t *psi_times(parser_t *left, parser_t *right)
psi_transpose    361 moa_func.c       parser_t *psi_transpose(parser_t *arg1, parser_t *arg2)
purify           444 psi.c            int purify(expr_t *expr, expr_t *result)
purify_vect     1166 vect.c           vect_t *purify_vect(vect_t *vect)
rav_value         81 vect.c           double rav_value(vect_t *vect, int i, int *simple)
real_expr         63 vect.c           int real_expr(expr_t *expr)
real_vect         47 vect.c           int real_vect(vect_t *vect)
recursive_assign 592 code.c           recursive_assign(vect_t *vect, vect_t *res, char *op)
RECV               4 uni.h            #define RECV(ptr,size,proc)
rec_partition    199 part.c           rec_partition(statement_t *body)
rec_print_expr   148 output.c         rec_print_expr(expr_t *expr)
redall           465 psi.c            redall(expr_t *fa_expr, expr_t *result, int top, char *op, int inright)
reduce_extended    3 extended.c       reduce_extended(expr_t *expr, expr_t *result, int top, char *op, int inright)
reduction_init  1243 psi.c            reduction_init()
red_cat          408 psi.c            red_cat(expr_t *arg1, expr_t *arg2)
red_drop         357 psi.c            red_drop(expr_t *arg1, expr_t *arg2)
red_ident        164 ident.c          ident_t *red_ident(ident_t *ident)
red_pdrop        334 psi.c            red_pdrop(expr_t *arg1, expr_t *arg2)
red_psi          386 psi.c            expr_t *red_psi(expr_t *arg1, expr_t *arg2, s_expr_t *r_dim)
red_ptake        348 psi.c            red_ptake(expr_t *arg1, expr_t *arg2)
red_rav         1040 vect.c           s_expr_t *red_rav(vect_t *vect, int i)
red_reverse      371 psi.c            red_reverse(expr_t *arg2)
red_scalar_extend 298 psi.c            expr_t *red_scalar_extend(expr_t *expr)
red_s_expr       232 ident.c          s_expr_t *red_s_expr(s_expr_t *s)
red_take         318 psi.c            red_take(expr_t *arg1, expr_t *arg2)
report           152 parse.c          report(char *text)
resolve_rules     88 part.c           dist_t *resolve_rules()
ret_table         70 parse.c          ident_t **ret_table(int *size)
reverse_list      94 psi.c            reduced_t *reverse_list(reduced_t *list)
SCALAR           265 psi.h            #define SCALAR(s) (((s)->op==NOP)&&((s)->ident->type==CONSTANT))
scalar_extend    391 moa_func.c       expr_t *scalar_extend(expr_t *scalar, vect_t *shp)
search           137 lex.c            search(char *name, uchar *isname, int *index)
search_parameters 128 parse.c          search_parameters()
separate_reduced1559 code.c           reduced_t *separate_reduced(reduced_t *list)
SETALLOC         256 psi.h            #define SETALLOC(x) x|=0x08
SETCODED         251 psi.h            #define SETCODED(x) x|=0x01
SETDYNAMIC       235 psi.h            #define SETDYNAMIC(x) x|=0x10
SETGLOBAL        231 psi.h            #define SETGLOBAL(x) x|=0x20
SETPARAMETER     247 psi.h            #define SETPARAMETER(x) x|=0x02
SETSCANNED       260 psi.h            #define SETSCANNED(x) x|=0x10
SETSHAPE         243 psi.h            #define SETSHAPE(x) x|=0x04
SETUSED          239 psi.h            #define SETUSED(x) x|=0x08
simplify_s_expr  451 ident.c          s_expr_t *simplify_s_expr(s_expr_t *s)
simplify_vect    342 vect.c           vect_t *simplify_vect(vect_t *vect)
skip_line         56 lex.c            skip_line()
StandardizeSExpr  87 scalar.c         s_expr_t *StandardizeSExpr(s_expr_t *pseRoot) {
start_loop      1433 code.c           int start_loop(expr_t *var, expr_t *left, expr_t *right)
statement        797 parse.c          statement_t *statement()
statement_list   828 parse.c          statement_t *statement_list()
static_shps     1023 vect.c           int static_shps(vect_t *vect)
static_value     312 vect.c           int static_value(vect_t *vect)
stats            422 sys.c            stats()
sym_key           37 parse.c          #define sym_key(i) ((i)%MAXSYMHASH)
s_compare        670 ident.c          int s_compare(s_expr_t *s1, s_expr_t *s2)
s_expr_free      237 sys.c            s_expr_free(s_expr_t *s_expr)
s_op             471 ident.c          s_expr_t *s_op(int op, s_expr_t *left, s_expr_t *right)
s_vect           487 ident.c          vect_t *s_vect(s_expr_t *s)
tau             1309 vect.c           void tau(FILE *fd, expr_t *expr)
term             343 parse.c          parser_t *term()
unmark_statics    62 parse.c          unmark_statics()
UNSETALLOC       257 psi.h            #define UNSETALLOC(x) x&=~(0x08)
UNSETCODED       252 psi.h            #define UNSETCODED(x) x&=~(0x01)
UNSETDYNAMIC     236 psi.h            #define UNSETDYNAMIC(x) x&=~(0x10)
UNSETGLOBAL      232 psi.h            #define UNSETGLOBAL(x) x&=~(0x20)
UNSETPARAMETER   248 psi.h            #define UNSETPARAMETER(x) x&=~(0x02)
UNSETSCANNED     261 psi.h            #define UNSETSCANNED(x) x&=~(0x10)
UNSETSHAPE       244 psi.h            #define UNSETSHAPE(x) x&=~(0x04)
UNSETUSED        240 psi.h            #define UNSETUSED(x) x&=~(0x08)
update_locs      680 vect.c           update_locs(vect_t *vect, s_expr_t *drop)
var_access       258 parse.c          parser_t *var_access()
var_def          892 parse.c          var_def()
var_def_part     907 parse.c          var_def_part()
vect2array      1281 vect.c           vect_t *vect2array(char *name,vect_t *vect)
vector_const     919 parse.c          vector_const(ident_t *ident)
vector_const2    281 parse.c          ident_t *vector_const2()
vect_assign      990 vect.c           vect_assign(vect_t *vect, vect_t *res, char *op)
vect_cat         804 vect.c           vect_t *vect_cat(vect_t *left, vect_t *right)
vect_compare     919 vect.c           int vect_compare(vect_t *vect1, vect_t *vect2) 
vect_drop        656 vect.c           vect_t *vect_drop(vect_t *left, vect_t *right)
vect_free        164 sys.c            vect_free(vect_t *vect)
vect_len         503 vect.c           vect_t *vect_len(vect_t *vect)
vect_op          521 vect.c           vect_t *vect_op(int op, vect_t *left, vect_t *right)
vect_take        542 vect.c           vect_t *vect_take(vect_t *left, vect_t *right)
vect_unop        860 vect.c           vect_t *vect_unop(int op, vect_t *vect)
vSHAPE             2 macros.h         #define vSHAPE(vector) vector->shp
what_name         44 lex.c            char *what_name()
