SUBROUTINE MAIN ()
  REAL, DIMENSION (:), ALLOCATABLE :: DOPEA, DOPEB
  INTEGER I

  ALLOCATE (DOPEA(3:99))
  ALLOCATE (DOPEB(0:99))

  DO I = 0, 99
    DOPEB(I) = REAL (I)
  END DO

  CALL TEST (DOPEA, DOPEB)
END SUBROUTINE
  
